# Splash screen
image splscr_txt_presented_by = Text("presented by", size=72, color="#777", font="fonts/Galmuri11-Bold.ttf", xycenter=(0.5,0.4), yoffset=-30)
image splscr_txt_team_name = Text("귀여움은 정의다", size=128, color="#333", font="fonts/Galmuri11-Bold.ttf", xycenter=(0.5,0.5))
image splscr_txt_combined = Fixed("splscr_txt_presented_by", "splscr_txt_team_name")

# Background image definitions
image bg school classroom morning = ("bg/School_Classroom_Morning.png")
image bg school classroom afternoon = ("bg/School_Classroom_Afternoon.png")
image bg school cafeteria = ("bg/School_Cafeteria.png")
image bg school yard = ("bg/School_Yard.png")
image bg school hallway = ("bg/School_Hallway.png")
image bg school library morning = ("bg/School_Library_Bright.png")
image bg school library afternoon = ("bg/School_Library_Dark.png")
image bg school nurseoffice = ("bg/School_Nurseoffice.png")
image bg cafe lateafternoon = ("bg/Cafe_Afternoon.png")
image bg home bedroom night = ("bg/Home_Bedroom_Night.png")
image bg home kitchen = ("bg/Home_Kitchen_Night.png")
image bg white screen = ("bg/White_Screen.jpg")
image bg black screen = ("bg/Black_Screen.jpg")

# Character sprites image definitions
image nuri = Placeholder("girl")
image nuri say = Placeholder("girl")
image nuri smile = Placeholder("girl")
image nuri smile blush = Placeholder("girl")
image nuri disappointed = Placeholder("girl")
image nuri sad = Placeholder("girl")
image nuri shy = Placeholder("girl")
image nuri frown = Placeholder("girl")
image nuri angry = Placeholder("girl")
image nuri embarrassed = Placeholder("girl")

image hanl = Placeholder("girl")
image hanl say = Placeholder("girl")
image hanl smile = Placeholder("girl")
image hanl smile blush = Placeholder("girl")
image hanl disappointed = Placeholder("girl")
image hanl sad = Placeholder("girl")
image hanl shy = Placeholder("girl")
image hanl frown = Placeholder("girl")
image hanl angry = Placeholder("girl")
image hanl embarrassed = Placeholder("girl")