# Splash screen
image splscr_txt_presented_by = Text("presented by", size=72, color="#777", font="fonts/Galmuri11-Bold.ttf", xycenter=(0.5,0.4), yoffset=-30)
image splscr_txt_team_name = Text("귀여움은 정의다", size=128, color="#333", font="fonts/Galmuri11-Bold.ttf", xycenter=(0.5,0.5))
image splscr_txt_combined = Fixed("splscr_txt_presented_by", "splscr_txt_team_name")

# Background image definitions
image bg school classroom morning = ("bg/School_Classroom_Morning.png")
image bg school classroom afternoon = ("bg/School_Classroom_Afternoon.png")
image bg school cafeteria = ("bg/School_Cafeteria.png")
image bg school yard = ("bg/School_Yard.png")
image bg school hallway = ("bg/School_Hallway.png")
image bg school library morning = ("bg/School_Library_Bright.png")
image bg school library afternoon = ("bg/School_Library_Dark.png")
image bg school nurseoffice = ("bg/School_Nurseoffice.png")
image bg school rooftop = ("bg/School_Rooftop.png")
image bg cafe lateafternoon = ("bg/Cafe_Afternoon.png")
image bg home bedroom night = ("bg/Home_Bedroom_Night.png")
image bg home kitchen = ("bg/Home_Kitchen_Night.png")
image bg white screen = ("bg/White_Screen.jpg")
image bg black screen = ("bg/Black_Screen.jpg")
image bg hospital = ("bg/Hospital.png")

# Character sprites image definitions
image nuri = Crop((0, 0, 1500, 100), "images/nuri/nuri_base.png")
image nuri say = Crop((0, 0, 1500, 1000),"images/nuri/nuri_say.png")
image nuri smile = Crop((0, 0, 1500, 1000),"images/nuri/nuri_smile.png")
image nuri smile blush = Crop((0, 0, 1500, 1000),"images/nuri/nuri_smile_blush.png")
image nuri disappointed = Crop((0, 0, 1500, 1000),"images/nuri/nuri_disappointed.png")
image nuri sad = Crop((0, 0, 1500, 1000),"images/nuri/nuri_sad.png")
image nuri shy = Crop((0, 0, 1500, 1000),"images/nuri/nuri_shy.png")
image nuri frown = Crop((0, 0, 1500, 1000),"images/nuri/nuri_frown.png")
image nuri angry = Crop((0, 0, 1500, 1000),"images/nuri/nuri_angry.png")
image nuri embarrassed = Crop((0, 0, 1500, 1000),"images/nuri/nuri_embarrassed.png")

image hanl = Crop((0, 0, 1500, 1000),"images/hanl/hanl_base.png")
image hanl say = Crop((0, 0, 1500, 1000),"images/hanl/hanl_say.png")
image hanl smile = Crop((0, 0, 1500, 1000),"images/hanl/hanl_smile.png")
image hanl smile blush = Crop((0, 0, 1500, 1000),"images/hanl/hanl_smile_blush.png")
image hanl disappointed = Crop((0, 0, 1500, 1000),"images/hanl/hanl_disappointed.png")
image hanl sad = Crop((0, 0, 1500, 1000),"images/hanl/hanl_sad.png")
image hanl shy = Crop((0, 0, 1500, 1000),"images/hanl/hanl_shy.png")
image hanl frown = Crop((0, 0, 1500, 1000),"images/hanl/hanl_frown.png")
image hanl angry = Crop((0, 0, 1500, 1000),"images/hanl/hanl_angry.png")
image hanl embarrassed = Crop((0, 0, 1500, 1000),"images/hanl/hanl_embarrassed.png")
